<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Faker\Factory as Faker;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventSeeder extends Seeder
{
    public function run()
    {
        $faker = Faker::create();

        DB::table('events')->insert([
            [
                'title' => 'Tech Expo 2024',
                'venue' => 'Surabaya Convention Center',
                'date' => '2024-03-15',
                'start_time' => '09:00:00',
                'end_time' => '17:00:00',
                'description' => $faker->text(200),
                'booking_url' => null,
                'max_tickets' => 1000,
                'sold_tickets' => 0,
                'status' => 'available',
                'image' => 'assets/event/images.jpeg',
                'price' => 100000,
                'province_id' => 35,
                'regency_id' => 3578,
                'organizer_id' => 1, 
                'event_category_id' => 1,
                'active' => 1,
            ],
            [
                'title' => 'Music Concert 2024',
                'venue' => 'Gelora Bung Tomo',
                'date' => '2024-06-20',
                'start_time' => '19:00:00',
                'end_time' => '21:00:00',
                'description' => $faker->text(200),
                'booking_url' => null,
                'max_tickets' => 500,
                'sold_tickets' => 0,
                'status' => 'available',
                'image' => 'assets/event/music-fest-2024.png',
                'price' => 50000,
                'province_id' => 73,
                'regency_id' => 7371,
                'organizer_id' => 2,
                'event_category_id' => 2, 
                'active' => 1,
            ],
            [
                'title' => 'Business Conference 2024',
                'venue' => 'Novotel Surabaya',
                'date' => '2024-09-10',
                'start_time' => '08:00:00',
                'end_time' => '18:00:00',
                'description' => $faker->text(200),
                'booking_url' => null,
                'active' => 1,
                'max_tickets' => 1200,
                'sold_tickets'=> 0,
                'status' => 'available',
                'image' => 'assets/event/business.png',
                'price' => 0,
                'province_id' => 91,
                'regency_id' => 9107,
                'organizer_id' => 3,
                'event_category_id' => 3, 
            ],
            [
                'title' => 'Art Exhibition 2024',
                'venue' => 'Museum of Modern Art',
                'date' => '2024-07-25',
                'start_time' => '10:00:00',
                'end_time' => '17:00:00',
                'description' => $faker->text(200),
                'booking_url' => null,
                'max_tickets' => 800,
                'sold_tickets' => 0,
                'status' => 'available',
                'image' => 'assets/event/art-exhibition-placeholder.jpg',
                'price' => 150000,
                'province_id' => 91,
                'regency_id' => 9107,
                'organizer_id' => 4,
                'event_category_id' => 1,
                'active' => 1,
            ],
            [
                'title' => 'Food Festival 2024',
                'venue' => 'Food Court Surabaya Mall',
                'date' => '2024-12-05',
                'start_time' => '11:00:00',
                'end_time' => '22:00:00',
                'description' => $faker->text(200),
                'booking_url' => null,
                'max_tickets' => 2000,
                'sold_tickets' => 0,
                'status' => 'available',
                'image' => 'assets/event/food-festival.jpg',
                'price' => 30000,
                'province_id' => 31,
                'regency_id' => 3171,
                'organizer_id' => 5,
                'event_category_id' => 2, 
                'active' => 1,
            ],
            [
                'title' => 'AI Conference 2024',
                'venue' => 'Grand Ballroom Hilton Hotel',
                'date' => '2024-10-18',
                'start_time' => '09:00:00',
                'end_time' => '17:00:00',
                'description' => $faker->text(200),
                'booking_url' => null,
                'max_tickets' => 1500,
                'sold_tickets' => 0,
                'status' => 'available',
                'image' => 'assets/event/ai-conference-placeholder.png',
                'price' => 0,
                'province_id' => 36,
                'regency_id' => 3671,
                'organizer_id' => 6,
                'event_category_id' => 3, 
                'active' => 1,
            ],
            [
                'title' => 'Startup Summit 2024',
                'venue' => 'Sheraton Hotel',
                'date' => '2024-12-02',
                'start_time' => '09:00:00',
                'end_time' => '18:00:00',
                'description' => $faker->text(200),
                'booking_url' => null,
                'max_tickets' => 600,
                'sold_tickets' => 0,
                'status' => 'available',
                'image' => 'assets/event/startup-summit.png',
                'price' => 150000,
                'province_id' => 73,
                'regency_id' => 7306,
                'organizer_id' => 7,
                'event_category_id' => 3,
                'active' => 1,
            ],
            [
                'title' => 'Sports Meet 2024',
                'venue' => 'Bung Karno Stadium',
                'date' => '2025-01-10',
                'start_time' => '07:00:00',
                'end_time' => '15:00:00',
                'description' => $faker->text(200),
                'booking_url' => null,
                'max_tickets' => 3000,
                'sold_tickets' => 0,
                'status' => 'available',
                'image' => 'assets/event/sports-meet.jpg',
                'price' => 50000,
                'province_id' => 11,
                'regency_id' => 1116,
                'organizer_id' => 8,
                'event_category_id' => 2,
                'active' => 1,
            ],
            [
                'title' => 'Leadership Seminar 2024',
                'venue' => 'Marriott Hotel',
                'date' => '2024-12-12',
                'start_time' => '10:00:00',
                'end_time' => '16:00:00',
                'description' => $faker->text(200),
                'booking_url' => null,
                'max_tickets' => 500,
                'sold_tickets' => 0,
                'status' => 'available',
                'image' => 'assets/event/leadership-seminar.png',
                'price' => 250000,
                'province_id' => 18,
                'regency_id' => 1872,
                'organizer_id' => 9,
                'event_category_id' => 3,
                'active' => 1,
            ],
            [
                'title' => 'Photography Workshop 2024',
                'venue' => 'Creative Hub Jakarta',
                'date' => '2024-12-30',
                'start_time' => '09:00:00',
                'end_time' => '17:00:00',
                'description' => $faker->text(200),
                'booking_url' => null,
                'max_tickets' => 150,
                'sold_tickets' => 0,
                'status' => 'available',
                'image' => 'null',
                'price' => 100000,
                'province_id' => 73,
                'regency_id' => 7371,
                'organizer_id' => 10,
                'event_category_id' => 1,
                'active' => 1,
            ],

        ]);
    }
}
